"""
Chatbot logging and analytics module.

This module records:
- Timestamp
- User message
- Detected intent
- Conversation step
- Bot response
"""

import json
from datetime import datetime
from pathlib import Path


# -------------------------------------------------
# Project paths
# -------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[2]

LOGS_DIR = PROJECT_ROOT / "logs"

LOG_FILE = LOGS_DIR / "chatbot.log"


# -------------------------------------------------
# Initialize logging directory
# -------------------------------------------------

def initialize_logger():
    """Create the logs directory if it does not exist."""

    LOGS_DIR.mkdir(
        parents=True,
        exist_ok=True
    )


# -------------------------------------------------
# Log conversation
# -------------------------------------------------

def log_conversation(
    user_message,
    bot_response,
    intent="unknown",
    conversation_step="unknown"
):
    """
    Save a conversation event to the log file.

    Args:
        user_message (str): Message entered by the user
        bot_response (str): Response generated by chatbot
        intent (str): Detected intent
        conversation_step (str): Current dialogue step
    """

    initialize_logger()

    log_entry = {
        "timestamp": datetime.now().isoformat(
            timespec="seconds"
        ),
        "user_message": user_message,
        "intent": intent,
        "conversation_step": conversation_step,
        "bot_response": bot_response
    }

    with open(
        LOG_FILE,
        "a",
        encoding="utf-8"
    ) as file:

        file.write(
            json.dumps(log_entry, ensure_ascii=False)
            + "\n"
        )


# -------------------------------------------------
# Read logs
# -------------------------------------------------

def read_logs():
    """
    Read all conversation logs.

    Returns:
        list: List of log entries
    """

    initialize_logger()

    if not LOG_FILE.exists():
        return []

    logs = []

    with open(
        LOG_FILE,
        "r",
        encoding="utf-8"
    ) as file:

        for line in file:

            line = line.strip()

            if not line:
                continue

            try:
                logs.append(json.loads(line))

            except json.JSONDecodeError:
                continue

    return logs


# -------------------------------------------------
# Analytics
# -------------------------------------------------

def get_analytics():
    """
    Generate basic chatbot analytics.

    Returns:
        dict: Analytics information
    """

    logs = read_logs()

    if not logs:

        return {
            "total_messages": 0,
            "intents": {},
            "conversation_steps": {}
        }

    intent_counts = {}
    step_counts = {}

    for entry in logs:

        intent = entry.get(
            "intent",
            "unknown"
        )

        step = entry.get(
            "conversation_step",
            "unknown"
        )

        intent_counts[intent] = (
            intent_counts.get(intent, 0) + 1
        )

        step_counts[step] = (
            step_counts.get(step, 0) + 1
        )

    return {
        "total_messages": len(logs),
        "intents": intent_counts,
        "conversation_steps": step_counts
    }


# -------------------------------------------------
# Test
# -------------------------------------------------

if __name__ == "__main__":

    print("=" * 60)
    print("             LOGGER TEST")
    print("=" * 60)

    log_conversation(
        user_message="I want to register",
        bot_response="What is your name?",
        intent="register",
        conversation_step="name"
    )

    log_conversation(
        user_message="Hello",
        bot_response="Welcome!",
        intent="greeting",
        conversation_step="idle"
    )

    print("\nLogs:")

    for log in read_logs():

        print(json.dumps(
            log,
            indent=4
        ))

    print("\nAnalytics:")

    analytics = get_analytics()

    print(json.dumps(
        analytics,
        indent=4
    ))

    print("\nLogger test completed.")